name: explore
description: "A mobile application that allows users to view a list of countries, see detailed information about a selected country (such as states, country code, flag, and capital)"
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter

  # Utility Packages
  http: ^1.3.0
  intl: ^0.20.2
  smooth_page_indicator: ^1.2.0+3
  connectivity_plus: ^6.1.3

  # Icons
  iconsax: ^0.0.8
  cupertino_icons: ^1.0.8

  # State Management
  get: ^4.7.1
  lottie: ^3.3.1
  cached_network_image: ^3.4.1
  shimmer: ^3.0.0
  carousel_slider: ^5.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  #--------------- LOCAL ASSETS ------------------#
  assets:
    - assets/logos/

  #--------------- LOCAL FONTS ------------------#
  fonts:
    - family: Axiforma
      fonts:
        - asset: assets/fonts/Axiforma-Light.ttf
          weight: 300
        - asset: assets/fonts/Axiforma-Regular.ttf
          weight: 400
        - asset: assets/fonts/Axiforma-Italic.ttf
          style: italic
        - asset: assets/fonts/Axiforma-Medium.ttf
          weight: 500
        - asset: assets/fonts/Axiforma-MediumItalic.ttf
          weight: 500
          style: italic
        - asset: assets/fonts/Axiforma-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Axiforma-Bold.ttf
          weight: 800
